server:
  build: .
  links:
    - db
  ports:
    - "8000:80"
  volumes:
    - ./public/:/var/www/html
    - ./logs/:/var/log/apache2
  environment:
    APACHE_MODULES: rewrite
db:
  image: mysql:5.7
  volumes:
    - ./resources/:/docker-entrypoint-initdb.d/
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: webservice
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: webservice